name: server_application
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

dependencies:
  args: ^2.4.0
  shelf: ^1.4.1
  shelf_router: ^1.1.0

dev_dependencies:
  http: ^1.2.2
  lints: ^4.0.0
  test: ^1.25.7
